FirstNumber = int(input("Enter first number:"))
SecondNumber = int(input("Enter second number:"))
print("addition of two given numbers:", FirstNumber + SecondNumber)
print("Subtraction of two given numbers:", FirstNumber - SecondNumber)
print("Multiplication of two given numbers:", FirstNumber * SecondNumber)
print("Division of two given numbers:", FirstNumber/SecondNumber)
